Question-1:
Write a Python program that will read a sequence of alphabets in lowercase  
separated by spaces in a single line according to the ASCII Table.

Your program should print a list of missing alphabets within the range of  
the given first alphabet and last alphabet. However, if there are no  
missing alphabets in between the range, then your program should print the  
given alphabets as a list.

================================================
Sample Input 1:
a b e f i k m n p

Sample Output 1:
['c', 'd', 'g', 'h', 'j', 'l', 'o']

Explanation 1: Here, in the given sequence the first alphabet is "a", last  
alphabet is "p" and 'c', 'd', 'g', 'h', 'j', 'l', 'o' are missing alphabets  
in between the range. So, the output will be  
['c', 'd', 'g', 'h', 'j', 'l', 'o'].

================================================
Sample Input 2:
a b c d e f g h

Sample Output 2:
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

Explanation 2: Here, in the given sequence the first alphabet is "a", last  
alphabet is "h" and there are no missing alphabets in between the range.  
So, the output will be ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'].

In [26]:
s=input().replace(" ","")

talika=[]
talika2=[]
talika3=[]

for i in s:
  talika.append(ord(i))
  talika3.append(i)

for j in range(97,ord(s[-1])+1):
  if j not in talika:
    talika2.append(chr(j))


if len(talika2)==0:
  print(talika3)
else:
  print(talika2)

a b e f i k m n p
['c', 'd', 'g', 'h', 'j', 'l', 'o']

Write a Python program that will take your Student ID as an input and print  
a dictionary, where the keys will be the unique digits from your given  
Student ID and the value will be a list of tuples according to the  
following.

Here, every tuple will hold two indices, where the first index will hold  
the index of that digit's Nth occurrence in the given Student ID and the  
second index will hold the number of occurrences thus far or the Nth value.

===============================================
Sample Input 1:
17301106

Sample Output 1:
{1: [(0, 1), (4, 2), (5, 3)], 7: [(1, 1)], 3: [(2, 1)], 0: [(3, 1), (6,  
2)], 6: [(7, 1)]}

Explanation 1: Here, in the given Student ID, unique digits are: 1, 7, 3, 0  
and 6. So, the keys will be 1, 7, 3, 0 and 6. Moving forward, in the given  
Student ID, 1 is in 0, 4 and 5 indices, therefore for the three  
occurrences, there will be a list of three tuples as a value for the key 1.  
So, the value will be [(Index: 0, Occurrence: 1), (Index: 4, Occurrence:  
2), (Index: 5, Occurrence: 3)] and so on similarly for the keys 7, 3, 0 and  
6.

================================================
Sample Input 2:
21166055

Sample Output 2:
{2: [(0, 1)], 1: [(1, 1), (2, 2)], 6: [(3, 1), (4, 2)], 0: [(5, 1)], 5:  
[(6, 1), (7, 2)]}

Explanation 2: Here, in the given Student ID, unique digits are: 2, 1, 6, 0  
and 5. So, the keys will be 2, 1, 6, 0 and 5. Furthermore, in the given  
Student ID, 2 has occurred in only index 0, therefore for the only  
occurrence, there will be a list of one tuple as a value for the key 2. So,  
the value will be [(Index: 0, Occurrence: 1)] and so on and so forth for  
the rest of the unique digit keys.

In [53]:
id=input()

check=[]
ind=[]
main=[]
oc_l=[]


for i in range(len(id)):
  if id[i] not in check:
    main.append(id[i])
    i_c=1
    oc=[i]
    i_c_l=[1]
    for j in range(i+1,len(id)):
      if id[i]==id[j]:
        i_c+=1
        i_c_l.append(i_c)
        oc.append(j)
    oc_l.append(i_c_l)
    ind.append(oc)
  check.append(id[i])

dic={}

for i in range(len(ind)):
  t2=[]
  for j in range(len(ind[i])):
    t2.append((ind[i][j],oc_l[ind.index(ind[i])][j]))
  dic[main[i]]=t2
print(dic)

{'1': [(0, 1), (4, 2), (5, 3)], '7': [(1, 1)], '3': [(2, 1)], '0': [(3, 1), (6, 2)], '6': [(7, 1)]}

In [29]:
{1: [(0, 1), (4, 2), (5, 3)], 7: [(1, 1)], 3: [(2, 1)], 0: [(3, 1), (6,
2)], 6: [(7, 1)]}

{'7', '0', '6', '1', '3'}

In [77]:
inp=input("ID Card:")
dit={}
count=0
for i in inp:
    if i not in dit.keys():
        dit[i]=[]
    else:
        continue
for x in range(len(inp)):
    new=[]
    for ke,val in dit.items():
        if inp[x]==ke:
            new.append(x)
            print(count)
            new.append(count)
            dit[ke]=tuple(new)
            count=count+1
print(dit)

ID Card:17301106
0
1
2
3
4
5
6
7
{'1': (5, 5), '7': (1, 1), '3': (2, 2), '0': (6, 6), '6': (7, 7)}

Question-3:
Write a function called slicing_function that takes two strings of equal  
length and an integer as arguments. The integer denotes where “crossing”  
should take place. You should return the strings after they have been  
crossed. Finally, print the answer as shown below.
================================================
Function call 1:
slicing_function("abcd","xypz",2)

Sample Output 1:
('abpz', 'xycd')


Explanation 1: In sample input 1, the crossing point is at 2. So the  
strings should cross after the 2nd value i.e. index 1. So, in the answer  
abpz means the first 2 letters are from abcd and the last 2 from xypz.  
Similarly, xycd means the first 2 letters are from xypz and the last 2 from  
abcd.

================================================
Function call 2:
slicing_function("ppp","ttt",1)

Sample Output 2:
('ptt', 'tpp')

Explanation 2:
In sample input 2, the crossing point is at 1. So the strings should cross  
after the 1st value i.e. index 0. So, in the answer ptt means the first  
value is from the string ppp and the rest from ttt. Similarly, tpp means  
the first value is from ttt and the later ones from ppp.

================================================

Sample Input 3:
slicing_function(“ppppp”,”cs”,2)

Sample Output 3:
Not Possible

Explanation 3:

In sample input 3, the strings are not of the same length, hence it is  
printing “Not Possible”.

In [66]:
def slicing_function(st1,st2,n):
  new1=""
  new2=""
  if len(st1)==len(st2):
    for i in range(len(st1)-n):
      new1=new1+st1[i]
      new2=new2+st2[i]
    i=i+1
    for j in range(n):
      new2=new2+st1[i+j]
      new1=new1+st2[i+j]
    return (new1,new2)
  else:
    return "Not Possible"

print(slicing_function("ppppp","cs",2))

Not Possible

('abpz', 'xycd')

Write a function named weird_sort() that will take a list of numbers as an 
argument and then RETURN  a new list that will follow the format given 
below.

Returned list format: [Largest, Smallest, Second largest, Second 
smallest,...so on...]

Then print the returned list in the function call. You can assume the 
length of the given list will always be even, there will be no duplicate 
values, and the values will be in range(0,101).

================================================
Function Call 01:
weird_sort([9, 3, 5, 7, 16, 20])

Sample Output 01:
[20, 3, 16, 5, 9, 7]

Explanation 01:
Largest value is 20 and the smallest value is 3. That's why in case of 
output, the values of the first two indices are 20 and 3. Similarly the 
second largest value and second smallest values are 16 and 5 respectively 
which are the values of  the following two indices.

================================================
Function Call 02:
weird_sort([10,20,30,40,50,60])

Sample Output 02:
[60, 10, 50, 20, 40, 30]

Explanation 02:
Largest value is 60 and the smallest value is 10. That's why in case of 
output, the values of the first two indices are 60 and 10. Similarly the 
second largest value and second smallest values are 50 and 20 respectively 
which are the values of  the following two indices.

In [76]:
def weird_sort(list1):
  list2=[]
  listF=[]
  for i in list1:
    list2.append(i)

  for i in range(len(list1)):
    if i%2==0:
      listF.append(max(list2))
      list2.remove(max(list2))
    else:
      listF.append(min(list2))
      list2.remove(min(list2))

  return listF

print(weird_sort([9, 3, 5, 7, 16, 20]))

[20, 3, 16, 5, 9, 7]

Question-2:
Write a Python program that will take a string where multiple words are 
separated by spaces as an input from the user. Print the words from the 
input string in a list format. Then, make a dictionary from the words where 
the unique keys will be the 1st character of the words and the values will 
be all the words that start with the same character contained within a 
tuple.
NOTE: For simplicity, you can treat uppercase and lowercase letter as one 
unique letter represented by lower case (i.e. may consider BOTH “P” and “p” 
to be “p”).

================================================
Sample Input 1:
"This  is hard but I can do it!"

Sample Output 1:
Words: ['This', 'is', 'hard', 'but', 'I', 'can', 'do', 'it!']
{'t': ('this',), 'i': ('is', 'i', 'it!'), 'h': ('hard',), 'b': 
('but',), 'c': ('can',), 'd': ('do',)}

Explanation 1:
The word “This” starts with lowercase letter ‘t’. Therefore “t” became the 
key and the only word that starts with “t” is “This”. So, “this” became the 
only tuple value it contains. The elements “is”, “it” and “I” start with 
“i”. Therefore “i” became the key and the three words “is”, “it” and “I” 
became its value contained in a tuple and so on.

================================================
Sample Input 2:
"I saw her selling sea shells in the sea shore"

Sample Output 2:
Words: 
['I', 'saw', 'her', 'selling', 'sea', 'shells', 'in', 'the', 'sea', 'shore']
{'i': ('i', 'in'), 's': 
('saw', 'selling', 'sea', 'shells', 'sea', 'shore'), 'h': ('her',), 't': 
('the',)}

Explanation 2:
“I” and “in” start with the same letter “i”. So they are the values for the 
key “i” enclosed in a tuple.  The elements “saw”, “selling” , “sea”, 
“shells”, “sea”, and “shore” all start with “s”. Therefore belong as a 
value to key “s”. Whereas, “her” and “the” were the only single elements 
that start with “h” and “t” so they were single tuple strings to keys “h” 
and “t”.

In [82]:
s=input().lower().split()
dic={}

for i in s:
  dic[i[0]]=i
print(s)
print(dic)

['this', 'is', 'hard', 'but', 'i', 'can', 'do', 'it!']
{'t': 'this', 'i': 'it!', 'h': 'hard', 'b': 'but', 'c': 'can', 'd': 'do'}