Task 8
Write a function called show_palindromic_triangle that takes a number as an argument and prints a Palindromic Triangle in the function.

[Must reuse the show_palindrome() function of the previous task]

=====================================================

Hints(1):
Need to use both print() and print( , end = " ") functions

=====================================================

Example1:
Function Call:
show_palindromic_triangle(5)
Output:

        1<br>
      1   2   1<br>
    1   2   3   2   1<br>
  1   2   3   4   3   2   1<br>
1   2   3   4   5   4   3   2   1<br>

=============================================================

In [2]:
n = int(input("How many lines would you like your triangle to be?  "))
for row in range(1,(n+1)):
  for s in range(n,0,-1):
    line = ""
    for column in range(1,(row+1)):
        line = line + str(column)
    for x in range(int(line[-1])):
        line = line + str(int(line[-1]) - 1)
    print(int(line)//10)

How many lines would you like your triangle to be?  4
1
1
1
1
121
121
121
121
12321
12321
12321
12321
1234321
1234321
1234321
1234321

In [20]:
n=int(input("Enter the number :"))

def show_palindromic_triangle(n):
    a=2*n
    for i in range(1,n+1):
        print(" "*a,end='')
        a-=2
        for j in range(1,i):
            print(str(j)+" ",end='')
        for k in range(i,0,-1):
            print(str(k)+" ",end='')
        print(end='\n')
show_palindromic_triangle(n)

Enter the number :4
        1
      1 2 1
    1 2 3 2 1
  1 2 3 4 3 2 1

ask 09
Write a function called area_circumference_generator that takes a radius of a circle as a function parameter and calculates its circumference and area. Then returns these two results as a tuple and prints the results using tuple unpacking in the function call accorrding to the given format.

[Must use tuple packing & unpacking]

=====================================================

Example1:
Function Call:
area_circumference_generator(1)
Output:
(3.141592653589793, 6.283185307179586)
Area of the circle is 3.141592653589793 and circumference is 6.283185307179586

====================================

Example2:
Function Call:
area_circumference_generator(1.5)
Output:
(7.0685834705770345, 9.42477796076938)
Area of the circle is 7.0685834705770345 and circumference is 9.42477796076938

====================================

Example3:
Function Call:
area_circumference_generator(2.5)
Output:
(19.634954084936208, 15.707963267948966)
Area of the circle is 19.634954084936208 and circumference is 15.707963267948966

In [6]:
def  area_circumference_generator(r):
  import math
  area=math.pi*r*r
  circum=2*math.pi*r
  return (area,circum)

n=1
print( area_circumference_generator(n))
print("Area of the circle is "+str(area_circumference_generator(n)[0])+" and circumference is "+str(area_circumference_generator(n)[1]))

(3.141592653589793, 6.283185307179586)
Area of the circle is 3.141592653589793 and circumference is 6.283185307179586

Task 10
Write a function called make_square that takes a tuple in the parameter as a range of numbers (starting point and ending point (included)). The function should return a dictionary with the numbers as keys and its squares as values.

=====================================================

Hints:
You need to declare a dictionary to store the result. You should use the range function to run the “for loop”.

=====================================================

Example1:
Function Call:
make_square((1,3))
Output:
{1: 1, 2: 4, 3: 9}

====================================

Example2:
Function Call:
make_square((5,9))
Output:
{5: 25, 6: 36, 7: 49, 8: 64, 9: 81}

In [8]:
def make_square(start,end):
  dict={}
  for i in range(start,end+1):
    dict[i]=i*i
  return dict

print(make_square(5,9))

{5: 25, 6: 36, 7: 49, 8: 64, 9: 81}

Task 11
Write a function called rem_duplicate that takes a tuple in the parameter and return a tuple removing all the duplicate values. Then print the returned tuple in the function call.

[Cannot use remove() or removed() for this task]

=====================================================

Hints:
Unlike lists, tuples are immutable so, the tuple taken as an argument cannot be modified. But list can be modified and lastly for returning the result use type conversion. You need to use membership operators (in, not in) for preventing adding any duplicates values.

=====================================================

Example1:
Function Call:
rem_duplicate((1,1,1,2,3,4,5,6,6,6,6,4,0,0,0))<br>
Output:
(1, 2, 3, 4, 5, 6, 0)

====================================

In [15]:
def rem_duplicate(tup):
  T1=()
  l1=[]
  l2=[]
  for i in range(len(tup)-1):
    for j in range(len(tup)):
      if tup[i]!=tup[j] and tup[i] not in l2:
        l1.append(tup[i])
        l2.append(tup[i])
  T1=tuple(l1)
  return T1

print(rem_duplicate((1,1,1,2,3,4,5,6,6,6,6,4,0,0,0)))

(1, 2, 3, 4, 5, 6, 0)

Write a python function that takes a list as an argument. Your task is to create a new list where each element can be present at max 2 times. Inside the function, print the number of elements removed from the given list. Finally, return the new list and print the result.

=====================================================

Hint: You may use list_name.count(element) to count the total number of times an element is in a list. list_name is your new list for this problem.

=====================================================

Function Call:
function_name([1, 2, 3, 3, 3, 3, 4, 5, 8, 8])
Output:
Removed: 2
[1, 2, 3, 3, 4, 5, 8, 8]
================================
Function Call:
function_name([10, 10, 15, 15, 20])
Output:
Removed: 0
[10, 10, 15, 15, 20]

In [16]:
def fun(k):
  l=list(set(k))
  final=[]
  hishab=0
  for i in l:
    if k.count(i)>=2:
      final.append(i)
      final.append(i)
      hishab=hishab+k.count(i)-2
    else:
      final.append(i)
  return (hishab,final)


res=fun([1, 2, 3, 3, 3, 3, 4, 5, 8, 8])
print("Removed: "+str(res[0]))
print(res[1])

Removed: 2
[1, 2, 3, 3, 4, 5, 8, 8]

Task 13
Write a python function that will perform the basic calculation (addition, subtraction, multiplication and division) based on 3 arguments. They are:

Operator ('+', '-', '/', '*')
First Operand (any number)
Second Operand (any number)
Your first task is to take these arguments as user input and pass the values to the function parameters.

Your second task is to write a function and performs the calculation based on the given operator. Then, finally return the result in the function call and print the result.

=====================================================

Input:
"+"
10
20
Function Call:
function_name("+", 10, 20)
Output:
30.0

================================

Input:
"*"
5.5
2.5
Function Call:
function_name("*", 5.5, 2.5)
Output:
13.75

In [22]:
def basic_calc(tup):
  if tup[0]=="+":
    return tup[1]+tup[2]
  elif tup[0]=="-":
    return tup[1]-tup[2]
  elif tup[0]=="*":
    return tup[1]*tup[2]
  elif tup[0]=="/":
    return tup[1]/tup[2]

oprt=input()
oprd1=float(input())
oprd2=float(input())
print(basic_calc((oprt, oprd1, oprd2)))

-
4.4
3
1.4000000000000004

Write a function which will take 2 arguments. They are:

Sentence
position
Your first task is to take these arguments as user input and pass these values to the function parameters.

Your second task is to implement the function and remove the characters at the index number which is divisible by the position (Avoid the index number 0 as it will always be divisible by the position, so no need to remove the index 0 character). Finally, add the removed characters at the end of the new string.

Return the value and then finally, print the new string at the function call.

[Cannot use remove() or removed() for this task]

=====================================================

Input:
"I love programming."
3
Function call:
function_name("I love programming.", 3)
Output:
I lveprgrmmngo oai.

==============================================

Input:
"Python is easy to learn. I love python."
6
Function call:
function_name("Python is easy to learn. I love python.", 6)
Output:
Pythonis eay to earn.I lov pythn. sl eo

In [24]:
def fun(st,n):
  s2=st[0]
  s3=""
  for i in range(1,len(st)):
    if i%n!=0:
      s2=s2+st[i]
    else:
      s3=s3+st[i]

  return (s2+s3)

sentence=input()
position=int(input())
print(fun(sentence,position))

I love programming.
3
I lveprgrmmngo oai.

Task 15
You have been hired as an app developer for the company. The company plans to make an app for a grocery store where the user can order groceries and see the total amount to be paid in the cart section.

To build this feature, you have to write a function that takes 2 arguments. They are:

order_items (must be a list)
location (default value should be set to "Dhanmondi")
Your first task is to take a list of items from the user. Pass the list into the function parameter along with the optional location (Use default argument technique). (Also, no need to take location as input, pass this any value you want.)

Your second task is to implement the function. In the function, create a dictionary for the items shown in the table. Calculate the total price of the items passed as a list to the function. Additionally, add a delivery fee of 30 taka if the location is Dhanmondi. Otherwise, add a delivery fee of 70 taka. Finally, return the value and print it.

Item	Price(Tk)
Rice	105
Potato	20
Chicken	250
Beef	510
Oil	85
=====================================================

Hint: The keys are the items and values are the corresponding price. Iterate the items in the list and check if the items in the list are available in the dictionary keys or not. If it is available, add the price.

=====================================================

Example1:
function_name(["Rice", "Beef", "Rice"], "Mohakhali")

total = 105 + 510 + 105 = 720 (Take the price of each item and add them.)
total = 720 + 70 = 790 (Finally, add the delivery fee based on the location.)

Input:
["Rice", "Beef", "Rice"]
Function Call:
function_name(["Rice", "Beef", "Rice"], "Mohakhali")
Output:
790

==============================================

Example2:

function_name(["Rice", "Beef", "Rice"])

total = 105 + 510 + 105 = 720 (Take the price of each item and add them.)
total = 720 + 30 = 750 (Since no location is passed in the parameter, it will use the default location-"Dhanmondi". For dhanmondi, delivery fee of 30 taka)

Input:
["Rice", "Beef", "Rice"]
Function Call:
function_name(["Rice", "Beef", "Rice"])
Output:
750

In [3]:
def fun(l,place="Dhanmondi"):
  price_list={
    "Rice":	105,
    "Potato":	20,
    "Chicken":	250,
    "Beef":	510,
    "Oil":	85}
  sum=0
  for i in l:
    sum=sum+price_list[i]
  if place=="Dhanmondi":
    return sum+30
  else:
    return sum+70
print(fun(["Rice", "Beef", "Rice"], "Mohakhali"))

790

In [ ]:
("Hi", 1, 2, 3, 3, "Hi", 'a', 'a', [1,2])

In [28]:
r=input().remove('"')
print(type(r))

("Hi", 1, 2, 3, 3, "Hi", 'a', 'a', [1,2])

AttributeError: ignored