#Mount Google drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:

def train_test_split(X,Y,test_size):
    rows=X.shape[0]
    train_size=1-test_size
    train=int(rows*train_size)
    
    f=X['Subject'][train]
    count1=0
    index1=train
    while X['Subject'][index1]==f:
        index1-=1
        count1+=1
    index2=train+1
    count2=0
    while X['Subject'][index2]==f:
        index2+=1
        count2+=1

    if count1>count2:
        train+=count2
    else:
        train-=count1

    test=rows-train
    print('Train Subject start and end:',X['Subject'][0],'To',X['Subject'][train])
    print('Test Subject start and end:',X['Subject'][train+1],'To',X['Subject'][rows-1])
    print('Train Percentage:',train/rows)
    X_train= X[:train+2]
    X_test= X[train+1:]
    Y_train = Y[:train+2]
    Y_test = Y[train+1:]
    return X_train,X_test,Y_train,Y_test

#numpy and pandas

In [ ]:
import numpy as np
import pandas as pd

df = pd.read_excel('/content/drive/MyDrive/Tanjila_mam/DS-Healthcare_version_2.xlsx')
target="Type"

In [ ]:
df.shape

(888817, 13)

In [ ]:
df[target].value_counts()

ischemic      581219
healthy       267360
arrhythmic     40238
Name: Type, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 888817 entries, 0 to 888816
Data columns (total 13 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   Subject  888817 non-null  object
 1   Type     888817 non-null  object
 2   Cycle    888817 non-null  int64
 3   Time     888817 non-null  float64
 4   RR-I     888817 non-null  float64
 5   HR       888817 non-null  float64
 6   R-H      888817 non-null  float64
 7   P-H      888817 non-null  float64
 8   QRS      888817 non-null  float64
 9   PRQ      888817 non-null  float64
 10  QT       888817 non-null  float64
 11  QTC      888817 non-null  float64
 12  ST       888817 non-null  float64
dtypes: float64(10), int64(1), object(2)
memory usage: 88.2+ MB

In [ ]:
df.head()

,Subject,Type,Cycle,Time,RR-I,HR,R-H,P-H,QRS,PRQ,QT,QTC,ST
0,E1,ischemic,1,1.072,0.932,64.377682,3.305,3.810,0.088,0.160,0.384,0.397762,0.296
1,E1,ischemic,2,2.004,1.004,59.760956,3.285,3.810,0.100,0.160,0.640,0.638724,0.540
2,E1,ischemic,3,3.008,0.996,60.240964,3.340,3.830,0.128,0.148,0.628,0.629260,0.500
3,E1,ischemic,4,4.004,1.016,59.055118,3.325,3.810,0.108,0.172,0.388,0.384933,0.280
4,E1,ischemic,5,5.020,0.972,61.728395,3.290,3.765,0.100,0.160,0.372,0.377320,0.272

In [ ]:
dataset = df
dataset.shape

(888817, 13)

In [ ]:
X = dataset.loc[:, dataset.columns!=target]     #removing target column (classes)
X = X.loc[:, X.columns!="Subject"]              #removing 'Subjec' column
X = X.loc[:, X.columns!="Cycle"]                #removing 'Cycle' column
#X = X.loc[:, X.columns!="Time"]                 #removing 'Time' column if you want, un-comment it
y = dataset[target]

list_of_feat = X.columns

In [ ]:
X.head()

    Time   RR-I         HR    R-H    P-H    QRS    PRQ     QT       QTC     ST
0  1.072  0.932  64.377682  3.305  3.810  0.088  0.160  0.384  0.397762  0.296
1  2.004  1.004  59.760956  3.285  3.810  0.100  0.160  0.640  0.638724  0.540
2  3.008  0.996  60.240964  3.340  3.830  0.128  0.148  0.628  0.629260  0.500
3  4.004  1.016  59.055118  3.325  3.810  0.108  0.172  0.388  0.384933  0.280
4  5.020  0.972  61.728395  3.290  3.765  0.100  0.160  0.372  0.377320  0.272

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)